### ISSUE TITLE
Working on macOS 🎉 but ….(incompatible with MacOS Input Fixes mod)

### ISSUE THREAD

**Issue by Minemaximus1023** [decce6/Ixeris#14]
There is an issue where if I press the Esc key the game has a chance to crash.

Here is the link to the log mclo.gs/9cPnS5q

**Comment by decce6** [comment]
```
[23:11:18] [Ixeris Event Polling Thread/INFO]: [STDERR]: java.lang.IllegalStateException: Tried to send packet not on client thread!
```

I noticed this line in the log. It did not directly cause the crash, but it indicates some mixin failures that *might* eventually be causing the crash.

Can you send the `debug.log`? It might contain more information on what caused this issue.

**Comment by decce6** [comment]
Please ignore my previous comment. I forgot `debug.log` does not exist on Fabric 😅

I can mostly confirm this is actually an incompatibility with the [MacOS Input Fixes](https://modrinth.com/mod/macos-input-fixes) mod. This mod registers GLFW callbacks directly in [native code](https://github.com/hamarb123/MCMacOSInputFixes/blob/a87248b8ce853765ef2ea86e2ed8f153063531a0/src/main/native/com_hamarb123_macos_input_fixes_MacOSInputFixesClientMod.mm#L213-L272), which is why Ixeris' [mixin](https://github.com/decce6/Ixeris/blob/3c6443ba97777492ab3b6c53d2780a7e4c1f0180/src/main/java/me/decce/ixeris/mixins/callbacks_threading/GLFWMixin.java) into `org.lwjgl.glfw.GLFW` does not work. Not yet sure how this could be fixed.

**Comment by decce6** [comment]
Hello! This has hopefully been fixed in 3.3.0 with 79a5758. Could you test if it works on your end?

**Comment by lunaynx** [comment]
This is still broken for me on macOS 26.1, Minecraft 1.21.8, Fabric Loader 0.18.0, Ixeris 3.6.3, and MacOS Input Fixes 1.10. But instead of game crashing, I just experience certain keys (e.g. Esc and Tab) being completely ignored.

Logs (does not seem to have anything relevant): https://mclo.gs/911ywF2
